## Required config files ##
sample_sheet: "./config/samples.csv"
resource_config : "./config/resources.yaml"

## Reference genome path ##
genome_path: "path/to/genome.fa"

## Host and infection accessions ##
coverage_groups:
  ## Each key is a group that mean cov will be calculated for. 
  ## Value should be the contig names in the reference genome. Must be list of strings.
  dmel: ["NC.004353", ""]
  wri: [""]
  wmel: [""]
  
  ## You can add as many genomes as you would like

## Genmap options ##
mappability:
  kmer_size: 150
  mismatches: 0
  score_cutoff: 1

## BAM filtering options ##
filter_bam:
  min_mapq: 20