## Required config files ##
sample_sheet: "./config/samples.csv"
resource_config : "./config/resources.yaml"

## Reference genome path ##
### MUST BE UNCOMPRESSED (blame genmap, not me) ###
genome_path: "data/test_genome.fna"

## Host and infection accessions ##
coverage_groups:
  ## Each key is a group that mean cov will be calculated for. 
  ## Value should be the contig names in the reference genome. Must be list of strings.
  dmel: ["asd"]
  wri: [""]
  wmel: [""]
  ## You can add as many genomes as you would like

## Roles to define host and symbiont relationships. Only one host is allowed.
roles:
  host: "dmel"
  symbionts: ["wmel","wri"]
  

## mappability options ##
mappability:
  kmer_size: 150
  mismatches: 0
  score_cutoff: 1

## BAM filtering options ##
filter_bam:
  min_mapq: 20