## Required config files ##
sample_sheet: "./config/samples.csv"
resource_config : "./config/resources.yaml"

## Reference genome path ##
### MUST BE UNCOMPRESSED (blame genmap, not me) ###
genome_path: "data/test_genome.fna"

## Host and infection accessions ##
coverage_groups:
  ## Each key is a group that mean cov will be calculated for. 
  ## Value should be the contig names in the reference genome. Should be string or list of strings.
  dmel: []
  wri: ""
  wmel: ""
  ## You can add as many genomes as you would like

## mappability options ##
mappability:
  kmer_size: 150
  mismatches: 0