name: Tests

on: 
  push:
    paths-ignore:
      - "config/**"
      - "**.md"
      

jobs:

  CI Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test/
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"